name: Java CI

on:
  push:
    branches: [ "rudie-rewrite" ]
  pull_request:
    branches: [ "rudie-rewrite" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'corretto'
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml
